### PR TITLE
Merge pull request #1 from redcross/master

### PR DESCRIPTION
**Pull request by chrissyha**
ADA compliance: increase contrast ratio 

needs review for #21! thanks, @cecilia-donnelly

### CODE REVIEW

**Comment by cecilia-donnelly** [comment]
Thanks @chrissyha!  It's a little hard for me to see the relevant changes here (it's a merge commit, so there's a bit more here than you might think).  Would you mind just commenting with what you changed so I can take a closer look?  Specifically, your message says "increase contrast ratio" but I don't see the word "ratio" or "contrast" in the diff, so a pointer would be helpful.  Thanks!

**Comment by chrissyha** [comment]
Hi @cecilia-donnelly, I don't see a diff =( It was several small changes of hex color codes for text and buttons to increase the contrast ratio between the foreground/background.  Sorry, but I think these changes somehow got lost in my use of github.

**Comment by kfogel** [comment]
Hi, @chrissyha.  Your comments in issue #21 are valuable even if we don't recover the changes... but it would be great to have the changes too if we can.  Do you still have the git repository on your laptop where you made the changes?  They're probably just sitting in there, waiting to be pushed up to https://github.com/chrissyha/smoke-alarm-portal.git (after which you could create a pull request, or we could go get the changes).

I looked at commit a5a9c0bd55e in your repository and saw the same thing that you and Cecilia saw: it's only a merge commit (it just takes changes from the upstream repository's master branch and merges them into your master branch).  The commit message mentions "ADA compliance: increase contrast ratio" -- those changes aren't in the merge commit, but I assume they reflect changes that you had locally and meant to put in their own commit.  If you still have them somewhere, though, we can get them upstream, and we're happy to help any way we can.

**Comment by chrissyha** [comment]
Hi Karl, Unfortunately, I do not have them locally on my laptop because I
was borrowing a friend's laptop for the hackathon =T

**Comment by kfogel** [comment]
Chrissy Ha <notifications@github.com> writes:
>Hi Karl, Unfortunately, I do not have them locally on my laptop
>because I
>was borrowing a friend's laptop for the hackathon =T

Ah, shucks.  No problem -- just your comments in the issue are still very helpful, and based on them we can reproduce the changes if necessary.  However, if you get a chance to ask that friend, or have access to the laptop again, please take a moment to see if the changes are there.  It'd be great if they are!

Best regards,
-Karl

**Comment by frankduncan** [comment]
Because this looks like it doesn't have a change, just closing out.

**Pull request closed without merging**
