### PR TITLE
Edit locales files; following up to #239

### PR DESCRIPTION
**Pull request by cecilia-donnelly**
As mentioned in #192, locales files end up with local mods after changes
to the text of any (translated) page.  Commit the changes to these files
that follow from the text changes in #239.

@OhMcGoo, I talked about this with @kfogel.  I know you two had discussed whether or not to change the locales files along with the front page text.  Because of #192 (and see in particular [my comment](https://github.com/redcross/smoke-alarm-portal/issues/192#issuecomment-327910028) there), I thought it was worthwhile to make this change, even before the Spanish translation is available.  After this change, the Spanish page has the old Spanish text and the English page has the new English text.    This prevents local mods showing up not just on the machines of other developers but also on the demo and prod servers.

### CODE REVIEW

**Comment by pjsier** [comment]
@cecilia-donnelly looks good! I ran this branch locally and it didn't change the locales files (it had changed some whitespace things for me before, but that could have been unrelated).

**Comment by frankduncan** [comment]
Ping @cecilia-donnelly 

Still learning this codebase!  Not quite sure how to test this one.  How do the locale files get loaded up so I'd see the change?

**Comment by kfogel** [comment]
@frankduncan: I don't think it's a matter of visiting the site to cause the locale files to get loaded up and thus you see some change via the browser.  Rather, the issue is that if some English text gets changed and that text is already marked as a translatable string, or for that matter if you add a new translatable string, then by the end of the build/deploy process, some locale files -- files you didn't touch -- will show up as modified according to `git status`.

This is because some step in the build process goes through and processes all the translatable strings: the ones that haven't changed and that have a corresponding translation are fine -- that all stays the same.  But any English strings that have been changed or added will result in the locale files (that is, the translation files) getting modified.  For example, if you change an English string, from the locale processor's point of view, the old English string disappeared, and a new (similar) English string was added, and the translation that corresponds to the old English string is now orphaned.

So this is a bug that you see at the command-line, not on the browser-facing site.

**Comment by frankduncan** [comment]
@kfogel While I understand what you're saying, I'm not quite sure how to see the behavior you're talking about on master.  My git status is empty after booting the server.  Is there some other command that I should be running to see the thing this PR fixes?

**Comment by kfogel** [comment]
Did you edit an English master string in some file and *then* launch the server?

**Comment by frankduncan** [comment]
This was obviated by #254

**Pull request closed without merging**
