### PR TITLE
 #208 Change serial to public id for clarity

### PR DESCRIPTION
**Pull request by frankduncan**
Because #217 is so out of date, created this PR to evaluate after a rebase.

### CODE REVIEW

**Comment by frankduncan** [comment]
Currently missing ```migrations/20160806-rename-serial-to-public-id.sql``` so can't merge until we have that file.

**Comment by kfogel** [comment]
Hey @raymondberg, do you have that file still (`migrations/20160806-rename-serial-to-public-id.sql`)?  I'm assuming you just forgot to `git add` it back when you made the [original PR](https://github.com/redcross/smoke-alarm-portal/pull/217).

Probably we could recreate it without too much trouble, but if you have it that would save some time.

**Comment by cecilia-donnelly** [comment]
In my copy I can see the migration file in 9b51d3e4.  I hope GitHub makes a link to it when I save this comment.

**Comment by cecilia-donnelly** [comment]
Alternatively, I believe it would look like:

```
module.exports = {
  up: function(queryInterface, Sequelize) {
      queryInterface.renameColumn("Requests", "serial", "public_id")
  },
  down: function(queryInterface, Sequelize) {
      queryInterface.renameColumn("Requests", "public_id", "serial")
  }
};
```

**Comment by cecilia-donnelly** [comment]
I'll defer to you, and add the file here.  Then if you test it I'm +1 to merge this.

**Pull request merged**
